import React from 'react';
import { Challenge } from '../types';

interface ChallengeModalProps {
  challenge: Challenge;
  onClose: () => void;
  onStart: () => void;
}

const ChallengeModal: React.FC<ChallengeModalProps> = ({ challenge, onClose, onStart }) => {
  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={onClose}></div>
      <div className="bg-surface border border-white/10 rounded-2xl w-full max-w-4xl max-h-[90vh] overflow-y-auto relative flex flex-col md:flex-row shadow-2xl">
        
        {/* Image Side */}
        <div className="w-full md:w-1/2 bg-black relative min-h-[300px]">
            {challenge.referenceImageUrl ? (
                <img 
                    src={challenge.referenceImageUrl} 
                    alt="Reference" 
                    className="w-full h-full object-cover"
                />
            ) : (
                <div className="w-full h-full flex items-center justify-center text-gray-600">No Image</div>
            )}
            <div className="absolute bottom-0 left-0 right-0 p-4 bg-gradient-to-t from-black to-transparent">
                <span className="text-xs font-mono text-gray-400 uppercase">Reference Image generated by Gemini</span>
            </div>
        </div>

        {/* Info Side */}
        <div className="w-full md:w-1/2 p-8 flex flex-col">
            <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
            </button>

            <div className="mb-6">
                <div className="inline-block px-3 py-1 rounded-full bg-accent/20 text-accent text-xs font-bold mb-2">DAILY CHALLENGE</div>
                <h2 className="text-3xl font-bold text-white mb-2">{challenge.title}</h2>
                <p className="text-gray-400 italic mb-4">Theme: {challenge.theme}</p>
                <p className="text-gray-300 leading-relaxed">{challenge.description}</p>
            </div>

            <div className="space-y-4 mb-8">
                <h3 className="text-sm font-bold text-gray-500 uppercase">Target Times</h3>
                <div className="grid grid-cols-3 gap-2 text-center">
                    <div className="p-3 bg-yellow-500/10 border border-yellow-500/30 rounded-lg">
                        <div className="text-yellow-500 font-bold">{challenge.goldTime}m</div>
                        <div className="text-xs text-yellow-500/70">GOLD</div>
                    </div>
                    <div className="p-3 bg-gray-400/10 border border-gray-400/30 rounded-lg">
                        <div className="text-gray-300 font-bold">{challenge.silverTime}m</div>
                        <div className="text-xs text-gray-400/70">SILVER</div>
                    </div>
                    <div className="p-3 bg-orange-700/10 border border-orange-700/30 rounded-lg">
                        <div className="text-orange-500 font-bold">{challenge.bronzeTime}m</div>
                        <div className="text-xs text-orange-500/70">BRONZE</div>
                    </div>
                </div>
            </div>

            <div className="mt-auto">
                <p className="text-sm text-gray-500 text-center mb-4">Launch your tool and start the timer when ready.</p>
                <button 
                    onClick={onStart}
                    className="w-full bg-white text-black hover:bg-gray-200 font-bold py-3 rounded-xl transition-colors"
                >
                    I'm Ready!
                </button>
            </div>
        </div>
      </div>
    </div>
  );
};

export default ChallengeModal;